name: Github Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./build_gh-pages.sh
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.github_token }}
